- hosts: all
  tasks:
    - name: Start zuul_console daemon
      zuul_console:

- hosts: localhost
  tasks:
    - name: Set zuul logs URL
      zuul_return:
        data:
          zuul:
            log_url: http://zuul-webinar.codilime.com/logs/{{ zuul.build }}

- name: Synchronize src repos to workspace directory.
  synchronize:
    dest: "."
    src: "{{ zuul.executor.src_root }}"
